language: php
php:
  - '7.4'
  - '8.0'

env:
  global:
    - XDEBUG_MODE=coverage

install:
  - composer self-update
  - make install

script: make lint test

after_success:
- travis_retry composer exec 'coveralls -v'

jobs:
  fast_finish: true
  allow_failures:
    - php: 8.0
